# Simplified GitHub Actions Deploy Step
# Use this to replace the problematic deployment step

    - name: 🚀 Deploy to Azure Container Apps (Simple)
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE_TAG=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        echo "Deploying image: $IMAGE_TAG"
        
        # Simple container app update with minimal parameters
        az containerapp update \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_TAG
        
        # Set environment variables separately
        az containerapp update \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --set-env-vars \
            NODE_ENV=production \
            PORT=3000 \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            REDIS_URL="${{ secrets.REDIS_URL }}" \
            NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
            NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
        
        # Configure ingress separately
        az containerapp ingress enable \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --type external \
          --target-port 3000 \
          --transport http || echo "Ingress already configured"
